name: Genera File XML Giornaliero

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Obbligatorio per salvare file nel repo

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install openai markdown

      - name: Run script
        env:
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
        run: python main.py

      - name: Commit e Push del file XML e titoli aggiornati
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Salvataggio articoli XML del giorno e aggiornamento titoli"
          file_pattern: "*.xml titoli.txt"
